create table fifa21 (
  sofifa_id integer PRIMARY KEY,
  name varchar,
  age integer,
  height_cm integer,
  weight_kg integer,
  nationality varchar,
  club varchar,
  league varchar,
  overall integer,
  value_eur integer,
  wage integer,
  position varchar,
  international_reputation integer,
  weak_foot integer,
  skill_moves integer,
  work_rate varchar,
  team_position varchar,
  team_jersey_nymber float,
  joined varchar,
  contract_valid float,
  pace varchar,
  shoooting varchar,
  passing varchar,
  dribbling varchar,
  defending varchar,
  physic varchar,
  attacking_crossing integer,
  attacking_heading integer,
  attacking_volleys integer,
  skill_curve integer,
  skill_fg integer,
  skill_long integer,
  movement_agility integer,
  movement_reactions integer,
  movement_balance integer,
  power_jumping integer,
  power_stamina integer,
  power_strength integer,
  mentality_aggression integer,
  mentality_vision integer,
  mentality_penalties integer,
  mentality_composure integer
);

insert into fifa21 (sofifa_id,
name,
age,
height_cm,
weight_kg,
nationality,
club,
league,
overall,
value_eur,
wage,
position,
international_reputation,
weak_foot,
skill_moves,
work_rate,
team_position,
team_jersey_nymber,
joined,
contract_valid,
pace,
shoooting,
passing,
dribbling,
defending,
physic,
attacking_crossing,
attacking_heading,
attacking_volleys,
skill_curve,
skill_fg,
skill_long,
movement_agility,
movement_reactions,
movement_balance,
power_jumping,
power_stamina,
power_strength,
mentality_aggression,
mentality_vision,
mentality_penalties,
mentality_composure ) values (
  '1',
  'Juan',
  '25',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1');
