---
title: "Librerías Importantes"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: true
    theme: spacelab

---

# Datos.

Usando la base de datos que esta en [esta liga](https://docs.google.com/spreadsheets/d/0Bw4a10rhk2QqaTZkUmQwaXU4aEE/edit?usp=sharing&ouid=101036910978943156470&resourcekey=0-RQa9gRpFX0x3z5bSJGn0Dg&rtpof=true&sd=true), generar los siguientes entregables:

# Necesidades de Negocio.

1. Un [Etl](https://en.wikipedia.org/wiki/Extract,_transform,_load) en R que tome los datos del formato en Excel y los transforme en un Data Frame que sea utilizable para análisis. (Ojo, el ETL tiene que asumir que puede pasar que le agreguen hojas al archivo de excel.)
2. Generar un motor sencillo que me indique el refugio más cercano a una coordenada dada.
3. Generar un dashboard que me ayude a identificar por localidad los refugios existentes.
4. Generar que el input de las coordenadas se maneje desde el dashboard.

# Fecha de Entrega

El proyecto se deberá entregar el Viernes 8 de Octubre antes de las 23:59 hrs. El método de entrega es através de un pull request a este repositorio. Dentro de la carpeta `proyectos/RespuestaDesastre` cada uno de los equipos deberá poner el código que se necesite para reproducir sus resultados.

# Aspectos a Calificar
  * Limpieza y Claridad de Código
  * Buenas prácticas de desarrollo
  * Reproducibilidad
  * Claridad de resultados
  * Inovación
