* Producto de Datos.

El objetivo del proyecto es implementar y empaquetar un producto de datos completo, para que puedan practicar las herramientas que hemos hecho durante el curso. Los temas a evaluar son los siguientes:

- Bash
- Python
- SQL
- APIs

* Requermientos

Se pide un producto de datos completo, esto es que tenga todos los componentes necesarios para que sea un análisis vivo y creciente de la información que va llegando al modelo. Esto compone principalmente X etapas.

** Base de datos de soporte
Los datos deben de guardarse en un postgreSQL, esto para replicar la necesidad de motores externos de bases de datos en la vida real.

** Carga de información inicial
La primer insersión de los datos a su base de datos debe de ser a través de Bash. Recomiendo usar la API que están construyendo para poder hacer la insersión de manera limpia y automática.

** Modelo como servicio Web
Su API debe tener un modelo de ML corriendo a manera de servicio, esto es, si le mando una nueva observación, debe de responder con la predicción que tiene para la misma.

** Carga de nuevos datos
Todo producto completo de datos, va a tener una actualización en los datos con los que se entrenan los modelos; su API debe de ser capaz de recibir estos nuevos datos y almacenarlos en su base de datos.

** Reentrenamiento del modelo
Pasado un tiempo y con suficientes datos nuevos, usualmente se busca un reentrenamiento del modelo, por lo cual su API debe de ser capaz de hacerlo con un request.


** Captura de resultados del modelo
Se busca además para entender el rendimiento y precisión del modelo que se registren los resultados, tal que el equipo de ciencia de datos pueda entender qué tan bien o mal está respondiendo.


** Ambiente totalmente reproducible
 "Corre en mi máquina" son palabras que no podrán articular como entrega en este proyecto. Ya que no entregan sus máquinas al cliente para que usen su modelo, tienen que aprender a empaquetar su API correctamente.

* Aspectos a evaluar

El día del examen final (7 de diciembre) se hará una presentación de 10 minutos en la que deberán mostrar tanto el problema de negocio que están resolviendo como la API funcionando, así como un paseo rápido por el código. Es mucho, así que sean muy precisos con su presentación.

** Limpieza de código

** Claridad de explicación del problema de negocio

** Documentación del código

** Funcionamiento del código
